In [1]:
import sys
sys.path.append('../')

In [2]:
from src.TVSD.TVSD import VolumeSlicingDataset, SlicedSegmentation

In [8]:
addr_eyes_0 = '/mnt/HD-LSDF/Medaka/segmentations/workshop/eye_decropped/01-508.tif'
addr_eyes_1 = '/mnt/HD-LSDF/Medaka/segmentations/workshop/eye_decropped_compressed/01-508.tif'
addr_eyes_2 = '/mnt/HD-LSDF/Medaka/segmentations/workshop/corrected_eyes/01-508.nii'

In [3]:
addr_vol = '/mnt/HD-LSDF/Medaka/segmentations/workshop/medaka_decropped/508.tif'

In [4]:
from univread import read as imread
import numpy as np

In [5]:
convo = {0: 0, 1: 1, 2: 1, 3: 0, 4: 0, 5: 3, 6: 3, 7: 4, 8: 4, 9: 5, 10: 5, 11: 6, 12: 6}

In [6]:
from tqdm.auto import tqdm

In [9]:
seg_sample_0 = SlicedSegmentation(addr_eyes_0, use_ram=False, label_converter=convo)

In [10]:
uniques = []
for i in tqdm(range(len(seg_sample_0))):
    uniques.append(np.unique(seg_sample_0[i]))

  0%|          | 0/1977 [00:00<?, ?it/s]

In [11]:
np.unique(np.concatenate(uniques))

array([0, 1, 3, 4, 5, 6])

In [13]:
seg_sample_0._contains_markup().sum()

181

In [14]:
seg_sample_1 = SlicedSegmentation(addr_eyes_0, use_ram=False)

In [15]:
uniques = []
for i in tqdm(range(len(seg_sample_1))):
    uniques.append(np.unique(seg_sample_1[i]))

  0%|          | 0/1977 [00:00<?, ?it/s]

In [16]:
np.unique(np.concatenate(uniques))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=uint16)

In [17]:
seg_sample_1._contains_markup().sum()

181

In [18]:
seg_sample_2 = SlicedSegmentation(addr_eyes_0, use_ram=True, label_converter=convo)

In [19]:
uniques = []
for i in tqdm(range(len(seg_sample_2))):
    uniques.append(np.unique(seg_sample_2[i]))

  0%|          | 0/1977 [00:00<?, ?it/s]

In [20]:
np.unique(np.concatenate(uniques))

array([0, 1, 3, 4, 5, 6])

In [21]:
seg_sample_2._contains_markup().sum()

181

In [ ]:
vd = VolumeSlicingDataset(volume=addr_vol, )